SET search_path TO bismark_passive;

-- Run generate_merge_functions.py to generate this file
\i drop_autogenerated.sql

SELECT execute('SELECT drop_matview('''||mv_name||''');') FROM matviews;
DROP TABLE matviews;

DROP FUNCTION refresh_matviews_node_latest(varchar, timestamp with time zone);
DROP FUNCTION refresh_matviews_context_latest(
    varchar, varchar, timestamp with time zone);

DROP FUNCTION refresh_matview_node_latest(
    name, varchar, timestamp with time zone, varchar);
DROP FUNCTION refresh_matview_context_latest(
    name, varchar, varchar, timestamp with time zone, varchar);
